"""Society-Core standalone runtime.

This package implements the v17 proof-obligation-carrying Society-Core runtime:
typed state, primitive actions, seeded replay, event-sourced history, validators,
registries, explicit social network diffusion, endogenous payment,
optional norm/institution detectors, real-platform calibration docking, statistical gates,
profile-conditioned product experience, demand-first user tasks, multi-community
forum affordances, subjective intent records, workspace-backed product experience,
guarded company workspace development, and event-grounded organizational
capability formation.
"""

from .calibration import build_calibration_docking_report, measure_forum_metrics
from .communities import DEFAULT_COMMUNITIES, initialize_communities
from .company_development import (
    CompanyDevelopmentRun,
    DEFAULT_COMPANY_CODING_MODEL,
    DevelopmentChangeUnit,
    HeuristicCompanyCodingAgent,
    OpenAICompanyCodingAgent,
    ProjectEdit,
    ProjectVerificationResult,
    ProjectWorkspaceManifest,
    apply_project_edits,
    apply_and_verify_project_edits,
    build_company_coding_agent,
    build_workspace_manifest,
    materialize_development_code_edits,
    run_project_verification,
)
from .company_optimizer import (
    DEFAULT_COMPANY_OPTIMIZER_MODEL,
    HeuristicCompanyOptimizer,
    OpenAICompanyOptimizer,
    build_company_optimizer,
)
from .company_safety import (
    CompanySafetyReview,
    DEFAULT_COMPANY_SAFETY_MODEL,
    HeuristicCompanySafetyReviewAgent,
    OpenAICompanySafetyReviewAgent,
    SafetyObligation,
    build_company_safety_review_agent,
)
from .claim_evidence import (
    ClaimWitness,
    EvaluationFreezeBoundary,
    EvidenceDebt,
    SocietyClaimCertificate,
    apply_claim_challenge,
    assess_evidence_debts,
    build_evaluation_freeze_boundary,
    build_society_claim_certificate,
    select_weakest_public_witness,
)
from .code_landing import (
    AcceptanceOracleSpec,
    CandidatePatch,
    CodeLandingTrajectory,
    CodeMaxRunResult,
    DevelopmentEpic,
    GuardedPatchDecision,
    IntegrationDecision,
    LandingDecision,
    LocalizationHypothesis,
    PatchSelectionDecision,
    PatchStrategyPlan,
    PatchValidationResult,
    RepoIntelligenceFabric,
    ReviewDecision,
    ReviewerFinding,
    SymbolLocation,
    WorkspaceExecutionProfile,
    build_acceptance_oracles,
    build_code_landing_trajectory,
    build_code_max_context_summary,
    build_development_epics,
    build_repo_intelligence_fabric,
    build_workspace_execution_profile,
    decide_landing,
    evaluate_integration_candidate,
    guard_selected_patch,
    localize_faults,
    plan_patch_strategies,
    review_selected_patch,
    run_code_max_runtime,
    select_best_patch,
    validate_candidate_patch,
    validate_candidate_patches,
)
from .construct_validity import construct_validity_suite_hash, run_construct_validity_suite
from .detectors import DetectorSuite
from .demand import (
    demand_weights_for_profile,
    project_task_demands,
    sample_user_task,
    substrate_task_demands,
)
from .evidence_pack import collect_platform_evidence_pack
from .experiments import build_seed_level_uncertainty_report, run_seed_batch, run_single_seed
from .historical_experiment import (
    HistoricalExperimentConfig,
    HistoricalExperimentReport,
    run_historical_product_experiment,
)
from .historical_products import (
    HistoricalProductCase,
    gitingest_2025_case,
    snowpack_2020_case,
    vite_2020_case,
)
from .matrix import default_scenario_matrix, run_scenario_matrix
from .org_adapter import (
    CompanyOptimizationProposal,
    artifact_from_public_org_release,
    build_company_public_feedback_report,
    extract_company_visible_public_traces,
    propose_company_optimization_from_public_feedback,
)
from .organizational_capabilities import (
    CAPABILITY_KIND_ORGANIZATIONAL,
    CAPABILITY_KIND_TECHNICAL_FIX,
    CapabilityEvent,
    CapabilityLedger,
    OrganizationalCapability,
    build_capability_ledger,
    capability_label,
    classify_capability_kind,
)
from .organization_experiment_repositories import (
    DatasetBoundaryAudit,
    ExperimentRepositoryBinding,
    audit_dataset_boundary,
    build_repository_binding,
    prepare_organizational_experiment_repositories,
    repository_preparation_manifest,
)
from .organization_experiment_analysis import (
    build_organization_portfolio_evidence,
)
from .registries import BoundedScoreRegistry, ClaimAudit, ParameterRegistry
from .runtime import SocietyConfig, SocietyRuntime
from .scenarios import inject_health_or_fatigue_shock, inject_public_conflict, inject_resource_shock, inject_rumor
from .platform_calibration import build_platform_calibration_report
from .product_experience import (
    apply_product_experience,
    artifact_price,
    simulate_product_experience,
    suggest_upgrades_from_experience,
)
from .real_product_experience import (
    RealProductExecutionObservation,
    RealProductExperienceTask,
    WorkspaceBackedProductExperienceHarness,
    build_real_product_experience_harness,
    execute_real_product_task,
    infer_real_product_experience_tasks,
    product_experience_packet_from_real_execution,
)
from .profiles import build_agent_profile
from .schemas import (
    Action,
    ActionBudgets,
    ActionKind,
    AgentProfile,
    AgentState,
    Artifact,
    BodyState,
    CognitiveState,
    ContentKind,
    Community,
    EventKind,
    ExternalEvent,
    LLMIntentRecord,
    MaterialResources,
    ProductExperiencePacket,
    ProductUsageStep,
    RunManifest,
    SocietyState,
    UpgradeSuggestion,
)
from .workspace_update import (
    WorkspaceFilePatch,
    WorkspacePackageInfo,
    WorkspacePatchResult,
    WorkspaceVerificationResult,
    apply_workspace_patches,
    load_workspace_package_info,
    run_workspace_verification,
    validate_workspace_package,
    workspace_update_mode,
)
from .workspace_agent import (
    AcceptanceOracle,
    CodingAgentLoopResult,
    CodingAgentPatchProposal,
    CodeLandingFailureReason,
    CodeLandingFunnelRecord,
    DEFAULT_WORKSPACE_CODING_EXPLORATION_ITERATIONS,
    DEFAULT_WORKSPACE_CODING_MAX_ITERATIONS,
    DEFAULT_WORKSPACE_CODING_MAX_SELECTED_FILES,
    DEFAULT_WORKSPACE_CODING_MODEL,
    DEFAULT_WORKSPACE_CODING_REASONING_EFFORT,
    DevelopmentTaskSpecV2,
    EngineeringOrganizationPlan,
    EngineeringWorkPackage,
    HeuristicWorkspaceCodingAgent,
    OpenAIWorkspaceCodingAgent,
    RepoIntelligencePack,
    ReproArtifact,
    ReproducerPlan,
    WorkspaceFileContext,
    build_development_intent_specs,
    build_development_task_specs_v2,
    build_engineering_organization_plan,
    build_repo_intelligence_pack,
    build_reproducer_plan,
    build_spec_maturity_gate,
    build_workspace_coding_agent,
    run_coding_agent_development_loop,
    run_coding_agent_development_loop_from_report_path,
    select_agent_context_files,
    select_workspace_files,
)

__all__ = [
    "Action",
    "ActionBudgets",
    "ActionKind",
    "AcceptanceOracle",
    "AgentProfile",
    "AgentState",
    "Artifact",
    "BodyState",
    "BoundedScoreRegistry",
    "ClaimAudit",
    "CognitiveState",
    "Community",
    "ContentKind",
    "CAPABILITY_KIND_ORGANIZATIONAL",
    "CAPABILITY_KIND_TECHNICAL_FIX",
    "CapabilityEvent",
    "CapabilityLedger",
    "ClaimWitness",
    "CodeLandingFailureReason",
    "CodeLandingFunnelRecord",
    "CompanyDevelopmentRun",
    "CompanyOptimizationProposal",
    "CompanySafetyReview",
    "CodingAgentLoopResult",
    "CodingAgentPatchProposal",
    "DEFAULT_COMPANY_CODING_MODEL",
    "DEFAULT_COMPANY_OPTIMIZER_MODEL",
    "DEFAULT_COMPANY_SAFETY_MODEL",
    "DEFAULT_COMMUNITIES",
    "DEFAULT_WORKSPACE_CODING_EXPLORATION_ITERATIONS",
    "DEFAULT_WORKSPACE_CODING_MAX_ITERATIONS",
    "DEFAULT_WORKSPACE_CODING_MAX_SELECTED_FILES",
    "DEFAULT_WORKSPACE_CODING_MODEL",
    "DEFAULT_WORKSPACE_CODING_REASONING_EFFORT",
    "DevelopmentChangeUnit",
    "DevelopmentTaskSpecV2",
    "DetectorSuite",
    "EngineeringOrganizationPlan",
    "EngineeringWorkPackage",
    "EventKind",
    "EvaluationFreezeBoundary",
    "EvidenceDebt",
    "ExternalEvent",
    "HeuristicCompanyCodingAgent",
    "HeuristicCompanyOptimizer",
    "HeuristicCompanySafetyReviewAgent",
    "HeuristicWorkspaceCodingAgent",
    "HistoricalProductCase",
    "HistoricalExperimentConfig",
    "HistoricalExperimentReport",
    "LLMIntentRecord",
    "MaterialResources",
    "OpenAICompanyOptimizer",
    "OpenAICompanyCodingAgent",
    "OpenAICompanySafetyReviewAgent",
    "OpenAIWorkspaceCodingAgent",
    "OrganizationalCapability",
    "ParameterRegistry",
    "ProjectEdit",
    "ProjectVerificationResult",
    "ProjectWorkspaceManifest",
    "ProductExperiencePacket",
    "ProductUsageStep",
    "RepoIntelligencePack",
    "ReproArtifact",
    "ReproducerPlan",
    "RealProductExecutionObservation",
    "RealProductExperienceTask",
    "RunManifest",
    "SafetyObligation",
    "SocietyConfig",
    "SocietyClaimCertificate",
    "SocietyRuntime",
    "SocietyState",
    "UpgradeSuggestion",
    "WorkspaceFilePatch",
    "WorkspaceFileContext",
    "WorkspaceBackedProductExperienceHarness",
    "WorkspacePackageInfo",
    "WorkspacePatchResult",
    "WorkspaceVerificationResult",
    "DatasetBoundaryAudit",
    "ExperimentRepositoryBinding",
    "apply_claim_challenge",
    "apply_product_experience",
    "apply_project_edits",
    "apply_and_verify_project_edits",
    "apply_workspace_patches",
    "artifact_price",
    "artifact_from_public_org_release",
    "audit_dataset_boundary",
    "build_calibration_docking_report",
    "build_organization_portfolio_evidence",
    "build_evaluation_freeze_boundary",
    "build_company_coding_agent",
    "build_company_public_feedback_report",
    "build_development_intent_specs",
    "build_development_task_specs_v2",
    "build_engineering_organization_plan",
    "build_company_optimizer",
    "build_company_safety_review_agent",
    "build_platform_calibration_report",
    "build_capability_ledger",
    "capability_label",
    "classify_capability_kind",
    "build_real_product_experience_harness",
    "build_repo_intelligence_pack",
    "build_repository_binding",
    "build_reproducer_plan",
    "build_spec_maturity_gate",
    "build_workspace_manifest",
    "build_workspace_coding_agent",
    "build_agent_profile",
    "build_seed_level_uncertainty_report",
    "build_society_claim_certificate",
    "collect_platform_evidence_pack",
    "construct_validity_suite_hash",
    "default_scenario_matrix",
    "execute_real_product_task",
    "extract_company_visible_public_traces",
    "gitingest_2025_case",
    "infer_real_product_experience_tasks",
    "propose_company_optimization_from_public_feedback",
    "prepare_organizational_experiment_repositories",
    "measure_forum_metrics",
    "materialize_development_code_edits",
    "inject_health_or_fatigue_shock",
    "inject_public_conflict",
    "inject_resource_shock",
    "inject_rumor",
    "initialize_communities",
    "run_seed_batch",
    "run_single_seed",
    "run_construct_validity_suite",
    "run_historical_product_experiment",
    "run_project_verification",
    "repository_preparation_manifest",
    "run_scenario_matrix",
    "run_workspace_verification",
    "run_coding_agent_development_loop",
    "run_coding_agent_development_loop_from_report_path",
    "sample_user_task",
    "assess_evidence_debts",
    "demand_weights_for_profile",
    "substrate_task_demands",
    "project_task_demands",
    "product_experience_packet_from_real_execution",
    "simulate_product_experience",
    "select_agent_context_files",
    "select_workspace_files",
    "select_weakest_public_witness",
    "snowpack_2020_case",
    "suggest_upgrades_from_experience",
    "validate_workspace_package",
    "vite_2020_case",
    "workspace_update_mode",
    "load_workspace_package_info",
    "AcceptanceOracleSpec",
    "CandidatePatch",
    "CodeLandingTrajectory",
    "CodeMaxRunResult",
    "DevelopmentEpic",
    "GuardedPatchDecision",
    "IntegrationDecision",
    "LandingDecision",
    "LocalizationHypothesis",
    "PatchSelectionDecision",
    "PatchStrategyPlan",
    "PatchValidationResult",
    "RepoIntelligenceFabric",
    "ReviewDecision",
    "ReviewerFinding",
    "SymbolLocation",
    "WorkspaceExecutionProfile",
    "build_acceptance_oracles",
    "build_code_landing_trajectory",
    "build_code_max_context_summary",
    "build_development_epics",
    "build_repo_intelligence_fabric",
    "build_workspace_execution_profile",
    "decide_landing",
    "evaluate_integration_candidate",
    "guard_selected_patch",
    "localize_faults",
    "plan_patch_strategies",
    "review_selected_patch",
    "run_code_max_runtime",
    "select_best_patch",
    "validate_candidate_patch",
    "validate_candidate_patches",
]
